# Generated by Django 4.2.27 on 2026-01-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlanDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='planning.dayplan')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
            ],
            options={
                'unique_together': {('day_plan', 'dish')},
            },
        ),
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
    ]
